//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFrontLab.DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreFrontProjectEntities : DbContext
    {
        public StoreFrontProjectEntities()
            : base("name=StoreFrontProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department_s> Department_s { get; set; }
        public virtual DbSet<Employee_s> Employee_s { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Xbox> Xboxes { get; set; }
        public virtual DbSet<XboxAccessory> XboxAccessories { get; set; }
        public virtual DbSet<XboxEmployee> XboxEmployees { get; set; }
        public virtual DbSet<XboxStatus> XboxStatuses { get; set; }
    }
}
