//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFrontLab.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xbox
    {
        public int XboxID { get; set; }
        public string XboxGameTitle { get; set; }
        public string Description { get; set; }
        public Nullable<int> AccessoriesID { get; set; }
        public Nullable<decimal> GamePrice { get; set; }
        public Nullable<int> XboxUnitsSold { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public int ReleaseCompany { get; set; }
        public string GameImage { get; set; }
        public int XboxStatusID { get; set; }
        public int DepartmentsID { get; set; }
    
        public virtual Department_s Department_s { get; set; }
        public virtual XboxAccessory XboxAccessory { get; set; }
        public virtual XboxStatus XboxStatus { get; set; }
    }
}
